### ISSUE TITLE
how did you finish this project?

### ISSUE THREAD

**Issue by Zhangeaky** [damienzh/dobot_ros_arm64#1]
helleo, your repo does me a great favor,thank you very much at first!
and may I know How did do that?
because I've download the ROS_demo from dobot's website ,there is nothing about arm64 neither the origin source code

**Comment by damienzh** [comment]
Hi, I just compile the source code on TX2.
PS. The official ROS demo does not include the source code, they are inside Dobot Demo.

**Comment by Zhangeaky** [comment]
yes, I've  downloaded the Dobot Demo,and saw about 11 items there,but which one is the source code  files that you complied on TX2? Thank you for  your guide

**Comment by damienzh** [comment]
Here's the source code. You can open this project with QT Creator on TX2.
![dobot_src](https://user-images.githubusercontent.com/13436906/82165925-78d13580-98e9-11ea-8cf0-2997a248e670.png)

**Comment by Zhangeaky** [comment]
deal! thanks a lot!
